apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flask-test
resources:
- ../../base
- ../overlays/prod

patches:
- path: patch.yaml
  target:
    kind: Deployment
    name: .*