apiVersion: v1
kind: Service
metadata:
  name: flask-app-v3-svc
  namespace: flask-test
spec:
  type: NodePort
  selector:
    app: flask-app-v3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30085